### ISSUE TITLE
Spanish accent marks

### ISSUE THREAD

**Issue by orangeiris** [Anadian/extract-documentation-comments#6]
I'm using this library to automatically generate markdown documentation updating a static web site every time I deploy my application. It works great. However, when the documentation block has one or more accent marks the all block is ignored.

Example:

Input:  
```
/**
## Some title

Parámetros
*/
void main(args[]){
}


/**
## Another title

Parameters
*/
```

--> In this case the letter `a` in "Parámetros" has an accent mark 

Output:
```
## Another title

Parameters
```

**Comment by Anadian** [comment]
Thanks for pointing this out; I'll take a look into adding proper full UTF8 support as soon as I can.

**Comment by Anadian** [comment]
As of version 0.3.0, extract-documentation-comments now supports [Latin-1 Supplemental characters](https://en.wikipedia.org/wiki/Latin-1_Supplement_%28Unicode_block%29) including accents; now your above example should work just fine. Let me know if you encounter any other issues. :)

**Comment by orangeiris** [comment]
It worked! Thanks
